apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bymseread.fullname" . }}-db-credentials
  labels:
    {{- include "bymseread.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-connection-string: {{ .Values.secrets.connectionStrings.postgres | b64enc | quote }}
  s3-connection-string: {{ .Values.secrets.connectionStrings.s3 | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bymseread.fullname" . }}-auth-credentials
  labels:
    {{- include "bymseread.labels" . | nindent 4 }}
type: Opaque
data:
  client-secret: {{ .Values.secrets.authn.clientSecret | b64enc | quote }}