apiVersion: v1
kind: Service
metadata:
  name: {{ include "bymseread.service.name" . }}
  labels:
    {{- include "bymseread.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
spec:
  type: {{ .Values.service.service.type }}
  ports:
    - port: {{ .Values.service.service.port }}
      targetPort: {{ .Values.service.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "bymseread.service.selectorLabels" . | nindent 4 }}