apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bymseread.service.name" . }}
  labels:
    {{- include "bymseread.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
  annotations:
    "helm.sh/hook-failed-policy": fail
spec:
  replicas: {{ .Values.replicaCount.service }}
  selector:
    matchLabels:
      {{- include "bymseread.service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bymseread.service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-service
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}/service:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ConnectionStrings__BymseReadPostgres
              valueFrom:
                secretKeyRef:
                  name: {{ include "bymseread.fullname" . }}-db-credentials
                  key: postgres-connection-string
            - name: ConnectionStrings__BymseReadS3
              valueFrom:
                secretKeyRef:
                  name: {{ include "bymseread.fullname" . }}-db-credentials
                  key: s3-connection-string
            - name: AuthN__Authority
              value: {{ .Values.authn.authority | quote }}
            - name: AuthN__ClientId
              value: {{ .Values.authn.clientId | quote }}
            - name: AuthN__ClientSecret
              valueFrom:
                secretKeyRef:
                  name: {{ include "bymseread.fullname" . }}-auth-credentials
                  key: client-secret
            - name: AuthN__MetadataAddress
              value: {{ .Values.authn.metadataAddress | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources.service | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}