// <auto-generated/>
#pragma warning disable CS0618
using BymseRead.Service.Client.WebApi.Books.Item.Bookmarks.LastPage;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BymseRead.Service.Client.WebApi.Books.Item.Bookmarks
{
    /// <summary>
    /// Builds and executes requests for operations under \web-api\books\{bookId}\bookmarks
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BookmarksRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The lastPage property</summary>
        public global::BymseRead.Service.Client.WebApi.Books.Item.Bookmarks.LastPage.LastPageRequestBuilder LastPage
        {
            get => new global::BymseRead.Service.Client.WebApi.Books.Item.Bookmarks.LastPage.LastPageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BymseRead.Service.Client.WebApi.Books.Item.Bookmarks.BookmarksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BookmarksRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/web-api/books/{bookId}/bookmarks", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BymseRead.Service.Client.WebApi.Books.Item.Bookmarks.BookmarksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BookmarksRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/web-api/books/{bookId}/bookmarks", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
