// <auto-generated/>
#pragma warning disable CS0618
using BymseRead.Service.Client.WebApi.Auth.Login;
using BymseRead.Service.Client.WebApi.Auth.Logout;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BymseRead.Service.Client.WebApi.Auth
{
    /// <summary>
    /// Builds and executes requests for operations under \web-api\auth
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuthRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The login property</summary>
        public global::BymseRead.Service.Client.WebApi.Auth.Login.LoginRequestBuilder Login
        {
            get => new global::BymseRead.Service.Client.WebApi.Auth.Login.LoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The logout property</summary>
        public global::BymseRead.Service.Client.WebApi.Auth.Logout.LogoutRequestBuilder Logout
        {
            get => new global::BymseRead.Service.Client.WebApi.Auth.Logout.LogoutRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BymseRead.Service.Client.WebApi.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/web-api/auth", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BymseRead.Service.Client.WebApi.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/web-api/auth", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
