// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BymseRead.Service.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BooksCollectionInfo : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The activeBooks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::BymseRead.Service.Client.Models.BookCollectionItem>? ActiveBooks { get; set; }
#nullable restore
#else
        public List<global::BymseRead.Service.Client.Models.BookCollectionItem> ActiveBooks { get; set; }
#endif
        /// <summary>The archivedBooks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::BymseRead.Service.Client.Models.BookCollectionItem>? ArchivedBooks { get; set; }
#nullable restore
#else
        public List<global::BymseRead.Service.Client.Models.BookCollectionItem> ArchivedBooks { get; set; }
#endif
        /// <summary>The newBooks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::BymseRead.Service.Client.Models.BookCollectionItem>? NewBooks { get; set; }
#nullable restore
#else
        public List<global::BymseRead.Service.Client.Models.BookCollectionItem> NewBooks { get; set; }
#endif
        /// <summary>The tlDrBooks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::BymseRead.Service.Client.Models.BookCollectionItem>? TlDrBooks { get; set; }
#nullable restore
#else
        public List<global::BymseRead.Service.Client.Models.BookCollectionItem> TlDrBooks { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BymseRead.Service.Client.Models.BooksCollectionInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BymseRead.Service.Client.Models.BooksCollectionInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BymseRead.Service.Client.Models.BooksCollectionInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activeBooks", n => { ActiveBooks = n.GetCollectionOfObjectValues<global::BymseRead.Service.Client.Models.BookCollectionItem>(global::BymseRead.Service.Client.Models.BookCollectionItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "archivedBooks", n => { ArchivedBooks = n.GetCollectionOfObjectValues<global::BymseRead.Service.Client.Models.BookCollectionItem>(global::BymseRead.Service.Client.Models.BookCollectionItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "newBooks", n => { NewBooks = n.GetCollectionOfObjectValues<global::BymseRead.Service.Client.Models.BookCollectionItem>(global::BymseRead.Service.Client.Models.BookCollectionItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "tlDrBooks", n => { TlDrBooks = n.GetCollectionOfObjectValues<global::BymseRead.Service.Client.Models.BookCollectionItem>(global::BymseRead.Service.Client.Models.BookCollectionItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::BymseRead.Service.Client.Models.BookCollectionItem>("activeBooks", ActiveBooks);
            writer.WriteCollectionOfObjectValues<global::BymseRead.Service.Client.Models.BookCollectionItem>("archivedBooks", ArchivedBooks);
            writer.WriteCollectionOfObjectValues<global::BymseRead.Service.Client.Models.BookCollectionItem>("newBooks", NewBooks);
            writer.WriteCollectionOfObjectValues<global::BymseRead.Service.Client.Models.BookCollectionItem>("tlDrBooks", TlDrBooks);
        }
    }
}
#pragma warning restore CS0618
