// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace BymseRead.Service.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum BookStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "New")]
        #pragma warning disable CS1591
        New,
        #pragma warning restore CS1591
        [EnumMember(Value = "TlDr")]
        #pragma warning disable CS1591
        TlDr,
        #pragma warning restore CS1591
        [EnumMember(Value = "Archived")]
        #pragma warning disable CS1591
        Archived,
        #pragma warning restore CS1591
    }
}
