// <auto-generated/>
#pragma warning disable CS0618
using BymseRead.Service.Client.WebApi.Auth;
using BymseRead.Service.Client.WebApi.Books;
using BymseRead.Service.Client.WebApi.Files;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BymseRead.Service.Client.WebApi
{
    /// <summary>
    /// Builds and executes requests for operations under \web-api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WebApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The auth property</summary>
        public global::BymseRead.Service.Client.WebApi.Auth.AuthRequestBuilder Auth
        {
            get => new global::BymseRead.Service.Client.WebApi.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The books property</summary>
        public global::BymseRead.Service.Client.WebApi.Books.BooksRequestBuilder Books
        {
            get => new global::BymseRead.Service.Client.WebApi.Books.BooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The files property</summary>
        public global::BymseRead.Service.Client.WebApi.Files.FilesRequestBuilder Files
        {
            get => new global::BymseRead.Service.Client.WebApi.Files.FilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BymseRead.Service.Client.WebApi.WebApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/web-api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BymseRead.Service.Client.WebApi.WebApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/web-api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
