replicaCount:
  service: 1
  webClientApp: 1

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  webClientApp:
    type: ClusterIP
    port: 80
    targetPort: 80
    containerPort: 80

resources:
  service:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  webClientApp:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  dbmigrator:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

config:
  connectionStrings:
    postgres: "Server=postgres;Port=5432;Database=bymseread;User Id=postgres;Password=postgres;"
    s3: "http://minioadmin:minioadmin@localhost:19000/bymse-read"

ingress:
  enabled: true
  host: "example.com"
  tls: true
  tlsSecretName: "example-tls-secret"
  annotations: {}

authn:
  authority: ""
  clientId: ""
  clientSecret: ""
  metadataAddress: ""
